name: Dimensions CIE
favicon: null
layout_spectrum: 0.2654744496103376
typography_spectrum: 0.489524228265509
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.06836386560462415
  lightness: 0.6542068175040185
  saturation: 0.34077194472774863
  rhythmicContrast: 0.06975705083459616
purpose: []
